# Generated by Django 5.0.1 on 2024-03-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0012_rename_username_admin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='HistoricalInvoice',
        ),
        migrations.DeleteModel(
            name='HistoricalItem',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
